### PR TITLE
Add Python3 support

### PR DESCRIPTION
**Pull request by Recursing**
Edits:
 - Replace print statement with print function
 - Replace xrange with range
 - Replace iter* in dict methods (e.g. iteritems())
 - Replace generator.next() with next(generator) (available since python 2.6 release in 2008)
 - Explicit id based hash function for Pmf (see #19 )

All changes have been tested both on python3 and on python2, in python2 using range instead of xrange (items() instead of iteritems(), and so on) doesn't seem to cause significant increased memory usage or performance regressions

### CODE REVIEW

**Comment by Recursing** [comment]
The `id` based hash of Pmf (and the `__eq__` overloaded to be probabilistic) can give problems when used with normal python dictionaries or built-ins, that assume the standard behavior from those function, see https://docs.python.org/3.8/reference/datamodel.html#object.__hash__ 

> If a class defines mutable objects and implements an __eq__() method, it should not implement __hash__(), since the implementation of hashable collections requires that a key’s hash value is immutable (if the object’s hash value changes, it will be in the wrong hash bucket).

**Comment by AllenDowney** [comment]
Thank you!

**Comment by Recursing** [comment]
Thank you for this awesome book! Can't wait to read the second version!

**Comment by SvenAG** [comment]
Thank you, this also fixes the issue with the mixtures of dice in chapter 5!

**Pull request merged**
